# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = 'debian/buster64'
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "lua.example.com"
  config.vm.synced_folder "./../", "/opt/app/", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "4"
  end
  config.vm.provider "libvirt" do |lv|
    lv.memory = "4096"
    lv.cpus = "4"
    lv.cputopology :sockets => '1', :cores => '2', :threads => '2'
  end
  config.vm.provision "shell", path: "provision.sh"

end
