version: '3.0'

services:
  app:
    image: twitter-harvester
    build: 
      context: './../'
      dockerfile: './docker/Dockerfile'
    volumes:
    - './../:/opt/app/'
    ports:
    - '8080:8080'
  graylog:
    image: graylog/graylog:3.1.3
    environment:
      GRAYLOG_PASSWORD_SECRET: 'wNJfMeW3ykAmLV8dMqp4Bkpzm444dsn7'
      GRAYLOG_ROOT_PASSWORD_SHA2: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'
      GRAYLOG_HTTP_EXTERNAL_URI: 'http://0.0.0.0:9000/'
    ports:
    - '9000:9000'
    links:
    - mongodb:mongo
    - elasticsearch
    depends_on:
    - mongodb
    - elasticsearch
  mongodb:
    image: mongo:4.2.1-bionic
  elasticsearch:
    image: elasticsearch:6.8.5
    environment:
      http.host: '0.0.0.0'
      transport.host: 'localhost'
      network.host: '0.0.0.0'
  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
    - './../docs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
    - '9090:9090'
  grafana:
    image: grafana/grafana:6.5.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
    - '3000:3000'
