{
 "title": "Twitter Harvester",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Erros",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "twitter_harvester_stats{type=\"error\"}"
    }
   ]
  },
  {
   "title": "Avisos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "twitter_harvester_stats{type=\"warning\"}"
    }
   ]
  },
  {
   "title": "Acessos",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "twitter_harvester_stats{type=\"access\"}"
    }
   ]
  },
  {
   "title": "Latências",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twitter_harvester_latency", "legendFormat": "{{name}}" }
   ]
  }
 ]
}